services:
  db:
    image: postgres:17.5-alpine3.20
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - my_db:$PGDATA

  library:
    build:
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  telegram_bot:
    build:
      context: .
    restart: always
    env_file:
      - .env
    command: >
      sh -c "python manage.py wait_for_db &&
            python library_api/bot.py"
    depends_on:
      - db
      - library

volumes:
  my_db:
