# Generated by Django 5.2.3 on 2025-07-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramprofile",
            name="chat_id",
            field=models.CharField(max_length=255),
        ),
    ]
